import { watch } from "node:fs";
import { createServer } from "node:http";
import { mkdir, readFile, readdir, rm, stat, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = __dirname;
const agentWorkspaceDir = path.join(rootDir, "agent-workspaces");
const port = Number(process.env.PORT || 3000);
const host = process.env.HOST || "127.0.0.1";

const mimeTypes = {
  ".html": "text/html; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".md": "text/markdown; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".webp": "image/webp",
  ".ico": "image/x-icon",
  ".txt": "text/plain; charset=utf-8"
};

function sendJson(res, status, payload) {
  const body = JSON.stringify(payload, null, 2);
  res.writeHead(status, {
    "Content-Type": "application/json; charset=utf-8",
    "Content-Length": Buffer.byteLength(body)
  });
  res.end(body);
}

function sendText(res, status, body, contentType = "text/plain; charset=utf-8") {
  res.writeHead(status, {
    "Content-Type": contentType,
    "Content-Length": Buffer.byteLength(body)
  });
  res.end(body);
}

async function readJson(req) {
  const chunks = [];
  for await (const chunk of req) chunks.push(chunk);
  const raw = Buffer.concat(chunks).toString("utf8");
  return raw ? JSON.parse(raw) : {};
}

function ensureInside(baseDir, targetPath) {
  const resolved = path.resolve(baseDir, targetPath || ".");
  const base = path.resolve(baseDir);
  if (resolved !== base && !resolved.startsWith(`${base}${path.sep}`)) {
    throw new Error("Path escapes site root");
  }
  return resolved;
}

function escapeHtml(value) {
  return String(value || "").replace(/[<>&"]/g, (char) => ({
    "<": "&lt;",
    ">": "&gt;",
    "&": "&amp;",
    '"': "&quot;"
  })[char]);
}

function slugify(value, fallback = "agent-project") {
  const cleaned = String(value || "")
    .toLowerCase()
    .replace(/[\u4e00-\u9fa5]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 48);
  return cleaned || `${fallback}-${Date.now().toString(36)}`;
}

function deriveProjectMeta(body) {
  const title = String(body.title || "").trim() || "Agent 项目";
  const slugSource = title !== "Agent 项目" ? title : body.prompt || "agent-project";
  return {
    type: "model",
    slug: slugify(slugSource, "agent-project"),
    title: title.slice(0, 120),
    summary: "由模型根据需求与规划自主生成，无预设模板。"
  };
}

function sanitizeAgentFilename(name) {
  const base = path.basename(String(name || "").trim());
  if (!base || base.startsWith(".") || base.includes("..")) return null;
  return base;
}

function parseEditPatchText(text) {
  const raw = String(text || "").trim();
  if (!raw) return { oldText: "", newText: "" };
  const patterns = [
    /---\s*OLD\s*---\r?\n([\s\S]*?)\r?\n---\s*NEW\s*---\r?\n([\s\S]*)/i,
    /<<<<<<<\s*OLD\r?\n([\s\S]*?)\r?\n=======\r?\n([\s\S]*?)(?:\r?\n>>>>>>>\s*NEW)?/i,
    /<<<<<<<\r?\n([\s\S]*?)\r?\n=======\r?\n([\s\S]*?)(?:\r?\n>>>>>>>)?/i
  ];
  for (const re of patterns) {
    const match = raw.match(re);
    if (match) return { oldText: match[1], newText: match[2] };
  }
  return { oldText: "", newText: raw };
}

function normalizeModelAgentFiles(rawFiles, body, project) {
  const out = {};
  for (const [name, content] of Object.entries(rawFiles || {})) {
    const safe = sanitizeAgentFilename(name);
    if (!safe) continue;
    out[safe] = String(content ?? "");
  }
  if (!out["index.html"]) {
    throw new Error("模型未返回 index.html");
  }
  out["README.md"] =
    `# ${project.title}\n\n` +
    `Generated by NEUX Agent Mode (model).\n\n` +
    `## Request\n\n${body.prompt || ""}\n\n` +
    `## Plan\n\n${body.plan || "No model plan."}\n`;
  out["agent-plan.md"] = body.plan || "No model plan.";
  return out;
}

async function createAgentProject(body) {
  if (!body.files || typeof body.files !== "object" || !body.files["index.html"]) {
    throw new Error("缺少模型生成的项目文件。Agent 模式仅支持模型自主生成，不使用预设模板。");
  }

  await mkdir(agentWorkspaceDir, { recursive: true });
  const project = deriveProjectMeta(body);
  const files = normalizeModelAgentFiles(body.files, body, project);

  const name = `${project.slug}-${Date.now().toString(36)}`;
  const dir = ensureInside(agentWorkspaceDir, name);
  await mkdir(dir, { recursive: true });
  const sourceFiles = Object.keys(files).filter((f) => !["README.md", "agent-plan.md"].includes(f));
  const logs = [
    {
      type: "ok",
      tool: "model_codegen",
      message: `模型自主生成：${sourceFiles.join(", ")}`
    },
    { type: "ok", tool: "create_folder", message: `agent-workspaces/${name}` },
    ...Object.keys(files).map((filename) => ({
      type: "ok",
      tool: "write_file",
      message: `${name}/${filename}`
    })),
    { type: "ok", tool: "open_preview", message: `/agent-workspaces/${name}/index.html` }
  ];
  await Promise.all(
    Object.entries(files).map(([filename, content]) => writeFile(path.join(dir, filename), content, "utf8"))
  );
  const fileTree = [
    { type: "folder", path: name },
    ...Object.keys(files).map((filename) => ({ type: "file", path: `${name}/${filename}` }))
  ];
  const manifest = {
    name,
    title: project.title,
    prompt: body.prompt || "",
    plan: body.plan || "",
    providerName: body.providerName || "",
    model: body.model || "",
    generatedBy: "model",
    path: `agent-workspaces/${name}`,
    previewUrl: `/agent-workspaces/${name}/index.html`,
    files: fileTree,
    logs,
    createdAt: new Date().toISOString()
  };
  await writeFile(path.join(dir, "agent-manifest.json"), JSON.stringify(manifest, null, 2), "utf8");
  manifest.files.push({ type: "file", path: `${name}/agent-manifest.json` });
  return manifest;
}

async function listWorkspaceFiles(dir, prefix = "") {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    if (entry.name === "agent-manifest.json") continue;
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await listWorkspaceFiles(full, rel)));
    } else {
      files.push(rel);
    }
  }
  return files;
}

async function startAgentSession(body) {
  await mkdir(agentWorkspaceDir, { recursive: true });
  const project = deriveProjectMeta(body);
  const name = `${project.slug}-${Date.now().toString(36)}`;
  const dir = ensureInside(agentWorkspaceDir, name);
  await mkdir(dir, { recursive: true });
  const relPath = `agent-workspaces/${name}`;
  const logs = [{ type: "ok", tool: "create_folder", message: relPath }];
  return {
    workspaceId: name,
    title: project.title,
    path: relPath,
    previewUrl: `/${relPath}/index.html`,
    files: [],
    logs
  };
}

async function executeAgentSessionTool(body) {
  const workspaceId = String(body.workspaceId || "").trim();
  if (!workspaceId) throw new Error("缺少 workspaceId");
  const dir = ensureInside(agentWorkspaceDir, workspaceId);
  const tool = String(body.tool || "").trim();
  const relPath = String(body.path || "").trim().replace(/^\/+/, "");
  const safe = relPath ? sanitizeAgentFilename(relPath) : null;

  if (tool === "write_file") {
    if (!safe) throw new Error("write_file 需要 path");
    const content = String(body.content ?? "");
    if (!content.trim()) {
      throw new Error("write_file 内容为空：请在 JSON 头后附带 markdown 代码块作为文件正文");
    }
    await writeFile(path.join(dir, safe), content, "utf8");
    return {
      message: `已写入 ${safe}（${content.length} 字符）`,
      log: { type: "ok", tool: "write_file", message: `${workspaceId}/${safe}` },
      files: await listWorkspaceFiles(dir)
    };
  }

  if (tool === "append_file") {
    if (!safe) throw new Error("append_file 需要 path");
    const content = String(body.content ?? "");
    if (!content.trim()) {
      throw new Error("append_file 内容为空：请在 JSON 头后附带 markdown 代码块");
    }
    const filePath = path.join(dir, safe);
    let existing = "";
    try {
      existing = await readFile(filePath, "utf8");
    } catch {
      existing = "";
    }
    await writeFile(filePath, existing + content, "utf8");
    return {
      message: `已追加 ${safe}（+${content.length} 字符，共 ${existing.length + content.length}）`,
      log: { type: "ok", tool: "append_file", message: `${workspaceId}/${safe}` },
      files: await listWorkspaceFiles(dir)
    };
  }

  if (tool === "delete_file") {
    if (!safe) throw new Error("delete_file 需要 path");
    const filePath = path.join(dir, safe);
    await unlink(filePath).catch(() => {
      throw new Error(`无法删除 ${safe}`);
    });
    return {
      message: `已删除 ${safe}`,
      log: { type: "ok", tool: "delete_file", message: `${workspaceId}/${safe}` },
      files: await listWorkspaceFiles(dir)
    };
  }

  if (tool === "edit_file") {
    if (!safe) throw new Error("edit_file 需要 path");
    const filePath = path.join(dir, safe);
    let oldText = String(body.oldText ?? "");
    let newText = String(body.newText ?? "");
    if (!oldText.trim()) {
      const patch = parseEditPatchText(body.content ?? "");
      oldText = patch.oldText || oldText;
      newText = patch.newText || newText;
    }
    if (!oldText.trim()) throw new Error("edit_file 需要 oldText");
    let text = await readFile(filePath, "utf8");
    if (!text.includes(oldText)) {
      throw new Error(`在 ${safe} 中未找到要替换的片段`);
    }
    text = text.replace(oldText, newText);
    await writeFile(filePath, text, "utf8");
    return {
      message: `已更新 ${safe}`,
      log: { type: "ok", tool: "edit_file", message: `${workspaceId}/${safe}` },
      files: await listWorkspaceFiles(dir)
    };
  }

  if (tool === "read_file") {
    if (!safe) throw new Error("read_file 需要 path");
    const filePath = path.join(dir, safe);
    const text = await readFile(filePath, "utf8");
    const max = 12000;
    const clipped = text.length > max ? `${text.slice(0, max)}\n…(已截断)` : text;
    return {
      message: clipped,
      log: { type: "ok", tool: "read_file", message: `${workspaceId}/${safe}` },
      files: await listWorkspaceFiles(dir)
    };
  }

  if (tool === "list_files") {
    const files = await listWorkspaceFiles(dir);
    return {
      message: files.length ? files.join("\n") : "(工作区暂无文件)",
      log: { type: "ok", tool: "list_files", message: `${files.length} 个文件` },
      files
    };
  }

  throw new Error(`未知工具：${tool}`);
}

function sanitizeAgentRelPath(relPath) {
  const normalized = String(relPath || "")
    .trim()
    .replace(/^\/+/, "")
    .replace(/\\/g, "/");
  if (!normalized || normalized.includes("..")) return null;
  const parts = normalized.split("/").filter(Boolean);
  if (parts.some((part) => part === "." || part === ".." || part.startsWith("."))) return null;
  return parts.join("/");
}

async function readAgentSessionFile(workspaceId, relPath) {
  const dir = ensureInside(agentWorkspaceDir, workspaceId);
  const safe = sanitizeAgentRelPath(relPath) || sanitizeAgentFilename(relPath);
  if (!safe) throw new Error("缺少 path");
  const filePath = ensureInside(dir, safe);
  const text = await readFile(filePath, "utf8");
  return { path: safe, content: text, size: text.length };
}

async function deleteAgentProject(workspaceId) {
  const id = String(workspaceId || "").trim();
  if (!id) throw new Error("缺少 workspaceId");
  const dir = ensureInside(agentWorkspaceDir, id);
  await rm(dir, { recursive: true, force: true });
  return { workspaceId: id };
}

async function bundleAgentProject(workspaceId) {
  const id = String(workspaceId || "").trim();
  if (!id) throw new Error("缺少 workspaceId");
  const dir = ensureInside(agentWorkspaceDir, id);
  const relFiles = await listWorkspaceFiles(dir);
  const files = {};
  for (const rel of relFiles) {
    const filePath = ensureInside(dir, rel);
    const text = await readFile(filePath, "utf8");
    files[rel] = text;
  }
  let title = id;
  try {
    const manifest = JSON.parse(await readFile(path.join(dir, "agent-manifest.json"), "utf8"));
    title = manifest.title || title;
  } catch {
    // ignore
  }
  return { workspaceId: id, title, files };
}

async function finishAgentSession(body) {
  const workspaceId = String(body.workspaceId || "").trim();
  if (!workspaceId) throw new Error("缺少 workspaceId");
  const dir = ensureInside(agentWorkspaceDir, workspaceId);
  const filesOnDisk = await listWorkspaceFiles(dir);
  if (!filesOnDisk.includes("index.html")) {
    throw new Error("工作区缺少 index.html，无法预览");
  }
  const indexText = await readFile(path.join(dir, "index.html"), "utf8");
  if (!indexText.trim()) {
    throw new Error("index.html 为空，请让 Agent 重新写入完整页面内容");
  }
  if (!/<\/html>/i.test(indexText)) {
    throw new Error("index.html 未写完（缺少 </html>），请继续生成或重试");
  }
  if (/<script\b/i.test(indexText) && !/<\/script>/i.test(indexText)) {
    throw new Error("index.html 脚本未写完（缺少 </script>），请继续生成或重试");
  }

  const project = deriveProjectMeta({ ...body, title: body.title || workspaceId });
  const relPath = `agent-workspaces/${workspaceId}`;
  const logs = Array.isArray(body.logs) ? body.logs : [];
  logs.push({
    type: "ok",
    tool: "open_preview",
    message: `/${relPath}/index.html`
  });

  const readme =
    `# ${body.title || project.title}\n\n` +
    `Generated by NEUX Agent Mode (Arena multi-turn).\n\n` +
    `## Request\n\n${body.prompt || ""}\n\n` +
    `## Plan\n\n${body.plan || ""}\n`;
  await writeFile(path.join(dir, "README.md"), readme, "utf8");
  await writeFile(path.join(dir, "agent-plan.md"), body.plan || "", "utf8");

  const fileTree = [
    { type: "folder", path: workspaceId },
    ...filesOnDisk.map((file) => ({ type: "file", path: `${workspaceId}/${file}` })),
    { type: "file", path: `${workspaceId}/README.md` },
    { type: "file", path: `${workspaceId}/agent-plan.md` }
  ];

  const manifest = {
    name: workspaceId,
    title: String(body.title || project.title).slice(0, 120),
    prompt: body.prompt || "",
    plan: body.plan || "",
    providerName: body.providerName || "",
    model: body.model || "",
    generatedBy: "arena",
    mode: "arena",
    path: relPath,
    previewUrl: `/${relPath}/index.html`,
    files: fileTree,
    logs,
    createdAt: new Date().toISOString()
  };
  await writeFile(path.join(dir, "agent-manifest.json"), JSON.stringify(manifest, null, 2), "utf8");
  manifest.files.push({ type: "file", path: `${workspaceId}/agent-manifest.json` });
  return manifest;
}

async function listAgentProjects() {
  await mkdir(agentWorkspaceDir, { recursive: true });
  const entries = await readdir(agentWorkspaceDir, { withFileTypes: true });
  const projects = [];
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const dir = path.join(agentWorkspaceDir, entry.name);
    const filesOnDisk = await listWorkspaceFiles(dir);
    const hasIndex = filesOnDisk.includes("index.html");
    const previewUrl = `/agent-workspaces/${entry.name}/index.html`;
    const fileTree = [
      { type: "folder", path: entry.name },
      ...filesOnDisk.map((file) => ({ type: "file", path: `${entry.name}/${file}` }))
    ];
    try {
      const manifest = JSON.parse(await readFile(path.join(dir, "agent-manifest.json"), "utf8"));
      manifest.workspaceFiles = filesOnDisk;
      if (!manifest.previewUrl && hasIndex) manifest.previewUrl = previewUrl;
      if (!Array.isArray(manifest.files) || !manifest.files.length) manifest.files = fileTree;
      projects.push(manifest);
    } catch {
      projects.push({
        name: entry.name,
        title: entry.name,
        path: `agent-workspaces/${entry.name}`,
        previewUrl: hasIndex ? previewUrl : "",
        workspaceFiles: filesOnDisk,
        files: fileTree,
        logs: [],
        createdAt: ""
      });
    }
  }
  return projects.sort((a, b) => String(b.createdAt).localeCompare(String(a.createdAt)));
}

const agentSiteWatchClients = new Set();
let agentSiteWatchTimer = null;
const agentSiteWatchPending = { full: false, workspaces: new Map() };

function broadcastAgentSiteEvent(payload) {
  const data = `data: ${JSON.stringify(payload)}\n\n`;
  for (const res of agentSiteWatchClients) {
    try {
      res.write(data);
    } catch {
      agentSiteWatchClients.delete(res);
    }
  }
}

function notifyAgentWorkspaceChange(workspaceId, changedPath = "") {
  if (workspaceId) {
    const entry = agentSiteWatchPending.workspaces.get(workspaceId) || { changedPaths: new Set() };
    if (changedPath) entry.changedPaths.add(changedPath);
    agentSiteWatchPending.workspaces.set(workspaceId, entry);
  } else {
    agentSiteWatchPending.full = true;
  }
  if (agentSiteWatchTimer) return;
  agentSiteWatchTimer = setTimeout(async () => {
    agentSiteWatchTimer = null;
    if (!agentSiteWatchClients.size) {
      agentSiteWatchPending.full = false;
      agentSiteWatchPending.workspaces.clear();
      return;
    }
    const doFull = agentSiteWatchPending.full;
    const workspaces = new Map(agentSiteWatchPending.workspaces);
    agentSiteWatchPending.full = false;
    agentSiteWatchPending.workspaces.clear();
    if (doFull || workspaces.size > 3) {
      broadcastAgentSiteEvent({ type: "projects", projects: await listAgentProjects() });
      return;
    }
    for (const [wsId, meta] of workspaces) {
      try {
        const dir = ensureInside(agentWorkspaceDir, wsId);
        const files = await listWorkspaceFiles(dir);
        const changedPaths = [...meta.changedPaths];
        const changedPath = changedPaths.length === 1 ? changedPaths[0] : "";
        broadcastAgentSiteEvent({ type: "workspace", workspaceId: wsId, files, changedPath });
      } catch {
        broadcastAgentSiteEvent({ type: "projects", projects: await listAgentProjects() });
        break;
      }
    }
  }, 180);
}

async function handleAgentProjectsWatch(req, res) {
  res.writeHead(200, {
    "Content-Type": "text/event-stream; charset=utf-8",
    "Cache-Control": "no-cache, no-store, must-revalidate",
    Connection: "keep-alive"
  });
  res.write(": connected\n\n");
  agentSiteWatchClients.add(res);
  req.on("close", () => agentSiteWatchClients.delete(res));
  res.write(`data: ${JSON.stringify({ type: "projects", projects: await listAgentProjects() })}\n\n`);
}

let agentWorkspaceWatcher = null;

function startAgentWorkspaceWatcher() {
  if (agentWorkspaceWatcher) return;
  void mkdir(agentWorkspaceDir, { recursive: true }).then(() => {
    agentWorkspaceWatcher = watch(agentWorkspaceDir, { recursive: true }, (_eventType, filename) => {
      if (!filename) {
        notifyAgentWorkspaceChange(null);
        return;
      }
      const normalized = String(filename).replace(/\\/g, "/");
      const workspaceId = normalized.split("/")[0];
      const changedPath = normalized.includes("/") ? normalized.slice(normalized.indexOf("/") + 1) : normalized;
      if (changedPath === "agent-manifest.json") return;
      notifyAgentWorkspaceChange(workspaceId, changedPath);
    });
    agentWorkspaceWatcher.on("error", () => {
      agentWorkspaceWatcher?.close();
      agentWorkspaceWatcher = null;
      setTimeout(startAgentWorkspaceWatcher, 3000);
    });
  });
}

async function handleAgentApi(req, res, pathname, searchParams) {
  if (req.method === "GET" && pathname === "/api/agent/projects/watch") {
    return handleAgentProjectsWatch(req, res);
  }
  if (req.method === "GET" && pathname === "/api/agent/projects") {
    return sendJson(res, 200, { ok: true, projects: await listAgentProjects() });
  }
  if (req.method === "GET" && pathname === "/api/agent/session/file") {
    const workspaceId = String(searchParams.get("workspaceId") || "").trim();
    const relPath = String(searchParams.get("path") || "").trim();
    const file = await readAgentSessionFile(workspaceId, relPath);
    return sendJson(res, 200, { ok: true, file });
  }
  if (req.method === "GET" && pathname === "/api/agent/project/bundle") {
    const workspaceId = String(searchParams.get("workspaceId") || "").trim();
    const bundle = await bundleAgentProject(workspaceId);
    return sendJson(res, 200, { ok: true, bundle });
  }
  if (req.method === "DELETE" && pathname === "/api/agent/project") {
    const workspaceId = String(searchParams.get("workspaceId") || "").trim();
    const deleted = await deleteAgentProject(workspaceId);
    notifyAgentWorkspaceChange(null);
    return sendJson(res, 200, { ok: true, ...deleted });
  }
  if (req.method === "POST") {
    const body = await readJson(req);
    if (pathname === "/api/agent/project/delete") {
      const workspaceId = String(body.workspaceId || searchParams.get("workspaceId") || "").trim();
      const deleted = await deleteAgentProject(workspaceId);
      notifyAgentWorkspaceChange(null);
      return sendJson(res, 200, { ok: true, ...deleted });
    }
    if (pathname === "/api/agent/run") {
      const result = await createAgentProject(body);
      notifyAgentWorkspaceChange(result.name);
      return sendJson(res, 200, { ok: true, result });
    }
    if (pathname === "/api/agent/session/start") {
      const session = await startAgentSession(body);
      notifyAgentWorkspaceChange(session.workspaceId);
      return sendJson(res, 200, { ok: true, session });
    }
    if (pathname === "/api/agent/session/tool") {
      const toolResult = await executeAgentSessionTool(body);
      notifyAgentWorkspaceChange(body.workspaceId, body.path || "");
      return sendJson(res, 200, { ok: true, ...toolResult });
    }
    if (pathname === "/api/agent/session/finish") {
      const result = await finishAgentSession(body);
      notifyAgentWorkspaceChange(body.workspaceId);
      return sendJson(res, 200, { ok: true, result });
    }
  }
  return sendJson(res, 404, { ok: false, error: "Unknown Agent API" });
}

async function serveStatic(req, res, pathname) {
  const decoded = decodeURIComponent(pathname === "/" ? "index.html" : pathname.replace(/^\/+/, ""));
  const filePath = ensureInside(rootDir, decoded);
  const info = await stat(filePath).catch(() => null);
  if (!info || !info.isFile()) return sendText(res, 404, "Not found");
  const ext = path.extname(filePath).toLowerCase();
  const body = await readFile(filePath);
  const headers = { "Content-Type": mimeTypes[ext] || "application/octet-stream" };
  if (filePath.includes(`${path.sep}agent-workspaces${path.sep}`)) {
    headers["Cache-Control"] = "no-store, no-cache, must-revalidate";
  }
  res.writeHead(200, headers);
  res.end(body);
}

const server = createServer(async (req, res) => {
  try {
    const url = new URL(req.url || "/", `http://${req.headers.host || `${host}:${port}`}`);
    if (url.pathname.startsWith("/api/agent/")) {
      await handleAgentApi(req, res, url.pathname, url.searchParams);
    } else {
      await serveStatic(req, res, url.pathname);
    }
  } catch (error) {
    sendJson(res, 500, { ok: false, error: error.message || "Server error" });
  }
});

startAgentWorkspaceWatcher();

server.listen(port, host, () => {
  console.log(`Static server running at http://${host}:${port}`);
});
